
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Dec 16 23:27:06 CET 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LEFTCB = 6;
  public static final int LOW = 13;
  public static final int SEMICOLON = 20;
  public static final int ELSE = 10;
  public static final int NOTEQ = 11;
  public static final int INTEGERCONST = 24;
  public static final int LEFTPAR = 17;
  public static final int BOOLEANCONST = 23;
  public static final int RIGHTPAR = 18;
  public static final int IF = 8;
  public static final int COLON = 21;
  public static final int ID = 22;
  public static final int RIGHTCB = 7;
  public static final int GR = 16;
  public static final int BOOLEAN = 5;
  public static final int GROREQ = 15;
  public static final int EOF = 0;
  public static final int REALCONST = 25;
  public static final int MAIN = 2;
  public static final int ELIF = 9;
  public static final int error = 1;
  public static final int LOWOREQ = 12;
  public static final int ASSIGN = 19;
  public static final int EQ = 14;
  public static final int INTEGER = 3;
  public static final int REAL = 4;
}

