
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 03 20:28:41 CET 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LEFTCB = 7;
  public static final int LOW = 14;
  public static final int SEMICOLON = 22;
  public static final int ELSE = 11;
  public static final int NOTEQ = 12;
  public static final int LEFTPAR = 19;
  public static final int RIGHTPAR = 20;
  public static final int IF = 9;
  public static final int COLON = 23;
  public static final int ID = 3;
  public static final int GR = 17;
  public static final int RIGHTCB = 8;
  public static final int BOOLEAN = 6;
  public static final int GROREQ = 16;
  public static final int EOF = 0;
  public static final int MAIN = 2;
  public static final int ELIF = 10;
  public static final int CONST = 18;
  public static final int error = 1;
  public static final int LOWOREQ = 13;
  public static final int ASSIGN = 21;
  public static final int EQ = 15;
  public static final int INTEGER = 4;
  public static final int REAL = 5;
}

